spring.application.name = demoChat
spring.datasource.url = jdbc:mysql://localhost:3306/demoChat_db

spring.datasource.username = demoChat
spring.datasource.password = dCh199312!

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true